aws:
  bucket: 'bucket-projeto-integrado-usjt'
file:
  path: 'newcsv.csv'
rabbit:
  host: 'localhost'
  port: 5672
  user: 'guest'
  pass: 'guest'
database:
  host: 'instanciabiusjt.c0arz9cwotau.us-east-1.rds.amazonaws.com'
  user: 
  pass: 
  schema: 'big_data'