aws:
  bucket: 'bucket-projeto-integrado-usjt'
file:
  path: 'newcsv.csv'
rabbit:
  host: '23.22.147.214'
  port: 5672
  user: ''
  pass: ''
database:
  host: ''
  user: saojudasbi
  pass: 
  schema: 'big_data'